Fixing IndexErrors in functions
When using the search_rows function to search an empty list of tasks (i.e. len(self.table.rows)==0), the application crashes displaying "IndexError: list index out of range". This commit adds an if statement to the search_rows function that checks if rows' last_index is greater than -1. I used last_index because it felt more readable, but the if statement could also check if len(rows) > 0 for a more direct reference.

This error can be replicated on version 2.2.0 by having an empty task list, pressing the " / " key, and then searching any character sequence.
Traceback for reference:

Traceback (most recent call last):
  File "~/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 78, in __init__
    self.loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "~/.local/lib/python3.8/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 68, in keypress
    return super().keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/urwid/container.py", line 1123, in keypress
    return self.footer.keypress((maxcol,),key)
  File "~/.local/lib/python3.8/site-packages/vit/multi_widget.py", line 59, in keypress
    return self.current_widget.keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/vit/command_bar.py", line 34, in keypress
    self.quit({'key': key, 'text': text})
  File "~/.local/lib/python3.8/site-packages/vit/command_bar.py", line 81, in quit
    self.event.emit('command-bar:keypress', data)  # remove focus from command bar
  File "~/.local/lib/python3.8/site-packages/vit/event.py", line 16, in emit
    listener(data)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 387, in command_bar_keypress
    self.search(reverse=(op == 'search-reverse'))
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 500, in search
    new_focus = self.search_rows(self.search_term_active, current_index, reverse)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 512, in search_rows
    start_matches = self.search_row_has_search_term(rows[start_index], search_regex)
IndexError: list index out of range

Fixing IndexError in keypress_home function

When using the keypress_home function to move to the top of an empty list of tasks (i.e. len(self.body)==0), the application crashes displaying "IndexError: Can't set focus, ListBox is empty". This commit adds an if statement to the keypress_home function that checks if self.body's length is greater than 0.

This error can be replicated on version 2.2.0 by having an empty task list and pressing the "gg" key combo

Traceback for reference:

Traceback (most recent call last):
  File "~/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 78, in __init__
    self.loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "~/.local/lib/python3.8/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 68, in keypress
    return super().keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 115, in keypress
    if self.action_manager_registrar.execute_handler(keys, size):
  File "~/.local/lib/python3.8/site-packages/vit/action_manager.py", line 24, in execute_handler
    handled_action['callback'](*args)
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 74, in keypress_home
    self.set_focus(0)
  File "~/.local/lib/python3.8/site-packages/urwid/listbox.py", line 547, in set_focus
    raise IndexError("Can't set focus, ListBox is empty")
IndexError: Can't set focus, ListBox is empty

Fixing IndexError in keypress_end function

When using the keypress_end function to move to the top of an empty list of tasks (i.e. len(self.body)==0), the application crashes displaying "IndexError: Can't set focus, ListBox is empty". This commit adds an if statement to the keypress_end function that checks if self.body's length is greater than 0.

This error can be replicated on version 2.2.0 by having an empty task list and pressing the "G" key.

Traceback for reference:

Traceback (most recent call last):
  File "~/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 78, in __init__
    self.loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "~/.local/lib/python3.8/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 68, in keypress
    return super().keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 115, in keypress
    if self.action_manager_registrar.execute_handler(keys, size):
  File "~/.local/lib/python3.8/site-packages/vit/action_manager.py", line 24, in execute_handler
    handled_action['callback'](*args)
  File "~/.local/lib/python3.8/site-packages/vit/task_list.py", line 506, in keypress_end
    super().keypress_end(size)
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 77, in keypress_end
    self.set_focus(len(self.body) - 1)
  File "~/.local/lib/python3.8/site-packages/urwid/listbox.py", line 547, in set_focus
    raise IndexError("Can't set focus, ListBox is empty")
IndexError: Can't set focus, ListBox is empty

Fixing IndexError in keypress_focus_valign_center function

When using the keypress_focus_valign_center function to move to the top of an empty list of tasks (i.e. len(self.body)==0), the application crashes displaying "IndexError: Can't set focus, ListBox is empty". This commit adds an if statement to the keypress_focus_valign_center function that checks if self.body's length is greater than 0.

This error can be replicated on version 2.2.0 by having an empty task list and pressing the "C" key.

Traceback for reference:

Traceback (most recent call last):
  File "~/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 78, in __init__
    self.loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "~/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "~/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "~/.local/lib/python3.8/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/vit/application.py", line 68, in keypress
    return super().keypress(size, key)
  File "~/.local/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 115, in keypress
    if self.action_manager_registrar.execute_handler(keys, size):
  File "~/.local/lib/python3.8/site-packages/vit/action_manager.py", line 24, in execute_handler
    handled_action['callback'](*args)
  File "~/.local/lib/python3.8/site-packages/vit/task_list.py", line 510, in keypress_focus_valign_center
    super().keypress_focus_valign_center(size)
  File "~/.local/lib/python3.8/site-packages/vit/base_list_box.py", line 96, in keypress_focus_valign_center
    self.set_focus(self.focus_position)
  File "~/.local/lib/python3.8/site-packages/urwid/listbox.py", line 576, in _get_focus_position
    raise IndexError("No focus_position, ListBox is empty")
IndexError: No focus_position, ListBox is empty

Making requested change to search_rows function

In the function search_rows, the if statement "if last_index > -1:" was changed to "if len(rows) > 0:" for better readability. These changes were requested in the pull request "Minor fixes involving IndexErrors #332".